/**
 * Ed25519 receipt signing.
 *
 * Boundary, stated once and enforced everywhere below:
 *
 *   The RECEIPT signing key and the PAYMENT signing key are different keys with
 *   different lifetimes and different blast radii. This module handles only the
 *   receipt key. It cannot construct, sign or submit a Hedera transaction, and
 *   it never sees a payer key.
 *
 * The key used by this demo is a throwaway generated by `npm run keygen`. It is
 * never a production issuer key, and the loader actively refuses paths that
 * point into the known production signing directories.
 */
import {
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  sign as edSign,
  verify as edVerify,
  type KeyObject,
} from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { signingInput, CANONICALIZATION_ID } from "../../shared-schemas/src/index.ts";

/**
 * Paths this project must never read a key from. Not a security control — a
 * root process can trivially bypass it — but a loud tripwire against the single
 * most damaging mistake available here: signing a demo artifact with the
 * production NOMOS issuer key.
 */
const FORBIDDEN_KEY_PREFIXES = [
  "/srv/nomos/signing",
  "/srv/nomos/verify",
  "/opt/nomos-",
  "/root/.hedera-",
  "/root/ops/sec_hedera_a1_quarantine",
];

export class SigningBoundaryError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SigningBoundaryError";
  }
}

export interface SignatureBlock {
  alg: "Ed25519";
  kid: string;
  signature_domain: string;
  canonicalization: string;
  public_key_hex: string;
  signature: string;
}

/**
 * Swappable signer. An HSM/KMS-backed implementation only has to satisfy this
 * interface — nothing downstream knows how the bytes get signed.
 */
export interface ReceiptSigner {
  readonly kid: string;
  readonly publicKeyHex: string;
  sign(domain: string, record: unknown): SignatureBlock;
}

/** Raw 32-byte Ed25519 public key from a KeyObject, as lowercase hex. */
function rawPublicKeyHex(pub: KeyObject): string {
  const der = pub.export({ format: "der", type: "spki" }) as Buffer;
  // SPKI for Ed25519 is a fixed 44-byte structure; the key is the final 32 bytes.
  if (der.length !== 44) {
    throw new SigningBoundaryError(`unexpected Ed25519 SPKI length ${der.length}; refusing to guess key offset`);
  }
  return der.subarray(12).toString("hex");
}

export class LocalEd25519Signer implements ReceiptSigner {
  readonly kid: string;
  readonly publicKeyHex: string;
  readonly #privateKey: KeyObject;

  constructor(privateKey: KeyObject, kid: string) {
    if (privateKey.asymmetricKeyType !== "ed25519") {
      throw new SigningBoundaryError(`expected an ed25519 key, got ${String(privateKey.asymmetricKeyType)}`);
    }
    this.#privateKey = privateKey;
    this.publicKeyHex = rawPublicKeyHex(createPublicKey(privateKey));
    this.kid = kid;
  }

  /** Generate an ephemeral key. Used by tests and by `npm run keygen`. */
  static generate(kid = "nomos-gx402-demo-ed25519-1"): LocalEd25519Signer {
    const { privateKey } = generateKeyPairSync("ed25519");
    return new LocalEd25519Signer(privateKey, kid);
  }

  /** Deterministic signer for fixtures: same seed in, same key out. */
  static fromSeed(seed32: Buffer, kid = "nomos-gx402-test-ed25519-1"): LocalEd25519Signer {
    if (seed32.length !== 32) throw new SigningBoundaryError("Ed25519 seed must be exactly 32 bytes");
    // PKCS#8 wrapper for a raw Ed25519 seed. Fixed 16-byte prefix, then the seed.
    const pkcs8 = Buffer.concat([
      Buffer.from("302e020100300506032b657004220420", "hex"),
      seed32,
    ]);
    return new LocalEd25519Signer(createPrivateKey({ key: pkcs8, format: "der", type: "pkcs8" }), kid);
  }

  /** Load a PKCS#8 PEM from disk, refusing production key paths outright. */
  static fromFile(path: string, kid: string): LocalEd25519Signer {
    const abs = resolve(path);
    for (const bad of FORBIDDEN_KEY_PREFIXES) {
      if (abs.startsWith(bad)) {
        throw new SigningBoundaryError(
          `refusing to load a signing key from ${abs}: this path belongs to the production stack ` +
            `(see docs/SECURITY_BOUNDARIES.md). Generate a demo key with \`npm run keygen\`.`,
        );
      }
    }
    return new LocalEd25519Signer(createPrivateKey(readFileSync(abs)), kid);
  }

  sign(domain: string, record: unknown): SignatureBlock {
    const msg = signingInput(domain, record);
    return {
      alg: "Ed25519",
      kid: this.kid,
      signature_domain: domain,
      canonicalization: CANONICALIZATION_ID,
      public_key_hex: this.publicKeyHex,
      signature: edSign(null, msg, this.#privateKey).toString("base64"),
    };
  }

  /** Export PKCS#8 PEM. Only used by `npm run keygen`, never by the runtime path. */
  exportPrivatePem(): string {
    return this.#privateKey.export({ format: "pem", type: "pkcs8" }) as string;
  }
}

/**
 * Verify a signature block against a record.
 *
 * `trustedKeys` maps kid -> raw public key hex. When supplied, the block's own
 * `public_key_hex` is checked against it and a mismatch fails. Verifying against
 * a key the document carries is not verification; it is transcription.
 */
export function verifySignature(
  record: unknown,
  block: SignatureBlock,
  expectedDomain: string,
  trustedKeys?: Readonly<Record<string, string>>,
): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];

  if (block?.alg !== "Ed25519") reasons.push("bad_alg");
  if (block?.canonicalization !== CANONICALIZATION_ID) reasons.push("bad_canonicalization");
  if (block?.signature_domain !== expectedDomain) reasons.push("domain_mismatch");
  if (!/^[0-9a-f]{64}$/.test(block?.public_key_hex ?? "")) reasons.push("bad_public_key");

  if (trustedKeys) {
    const known = trustedKeys[block?.kid ?? ""];
    if (!known) reasons.push("unknown_kid");
    else if (known !== block.public_key_hex) reasons.push("public_key_not_trusted");
  }

  if (reasons.length > 0) return { ok: false, reasons };

  try {
    const spki = Buffer.concat([
      Buffer.from("302a300506032b6570032100", "hex"),
      Buffer.from(block.public_key_hex, "hex"),
    ]);
    const pub = createPublicKey({ key: spki, format: "der", type: "spki" });
    const ok = edVerify(null, signingInput(expectedDomain, record), pub, Buffer.from(block.signature, "base64"));
    if (!ok) reasons.push("signature_invalid");
    return { ok, reasons };
  } catch (e) {
    return { ok: false, reasons: [`verify_error:${(e as Error).name}`] };
  }
}
