#!/usr/bin/env node
/**
 * Turn two funded EVM addresses into a working `.env`.
 *
 *   node tools/setup-env.ts
 *
 * Reads the two local demo keys, derives their EVM addresses, asks the public
 * mirror node which Hedera account ids the faucet created for them, and writes
 * `.env` (git-ignored) with those ids filled in.
 *
 * Read-only with respect to the chain: two GETs, no transaction. It refuses to
 * write anything if either account is missing, so a half-configured `.env`
 * cannot exist — a payment attempt against a half-configured demo is exactly
 * the kind of avoidable failure the one-payment budget cannot afford.
 *
 * The private keys are read only far enough to derive public addresses, and
 * neither the keys nor anything derived from them beyond those addresses is
 * written to `.env` or printed.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { PrivateKey } from "@x402/hedera";

import { fetchAccount, MIRROR_TESTNET_BASE } from "../packages/hedera-x402-adapter/src/mirror.ts";

const PRICE_ATOMIC = "5000000"; // 0.05 HBAR — valueless testnet token

interface Resolved {
  /** What goes into `.env` as pay_to / payer: an account id, or an EVM alias. */
  target: string;
  accountId: string | null;
  balance: bigint;
  evm: string;
  created: boolean;
}

/**
 * Resolve a local demo key to whatever the ledger currently knows about it.
 *
 * `allowAlias` is the difference between the two roles. The PAYER must exist and
 * be funded — it has to have HBAR to send, and no alias trick changes that. The
 * PAYEE may still be uncreated: a transfer to its EVM alias creates it (Hedera
 * auto-account creation), and since the alias is derived from a key we hold,
 * the created account is one we can open.
 */
async function resolveRole(role: "payer" | "payee", allowAlias: boolean): Promise<Resolved> {
  const keyPath = resolve(`.local/hedera-${role}.key`);
  if (!existsSync(keyPath)) throw new Error(`missing ${keyPath} — run: node tools/hedera-keygen.ts ${role}`);

  const key = PrivateKey.fromStringECDSA(readFileSync(keyPath, "utf8").trim());
  const evm = `0x${key.publicKey.toEvmAddress()}`;

  const account = await fetchAccount(evm, MIRROR_TESTNET_BASE);
  if (account && !account.deleted) {
    return {
      target: account.account,
      accountId: account.account,
      balance: BigInt(account.balance?.balance ?? 0),
      evm,
      created: true,
    };
  }

  if (allowAlias) {
    return { target: evm, accountId: null, balance: 0n, evm, created: false };
  }

  throw new Error(
    `${role} account not found for ${evm}\n` +
      `  → it must exist and hold HBAR before a payment can be made`,
  );
}

async function main(): Promise<void> {
  const payer = await resolveRole("payer", false);
  const payee = await resolveRole("payee", true);

  console.log(`payer : ${payer.target}  (${payer.evm})  balance ${payer.balance} tinybar`);
  console.log(
    payee.created
      ? `payee : ${payee.target}  (${payee.evm})  balance ${payee.balance} tinybar`
      : `payee : ${payee.target}  (not yet created — Hedera auto-account creation on first payment)`,
  );

  if (payer.balance < BigInt(PRICE_ATOMIC)) {
    throw new Error(`payer holds ${payer.balance} tinybar, needs at least ${PRICE_ATOMIC}`);
  }
  if (payer.evm.toLowerCase() === payee.evm.toLowerCase()) {
    throw new Error("payer and payee resolved to the same key — a self-payment proves nothing");
  }

  const env = `# Generated by tools/setup-env.ts — git-ignored, contains NO secrets.
# Account ids are public. Private keys live in .local/*.key (mode 0600).
NOMOS_GX402_NETWORK=hedera:testnet
NOMOS_GX402_MIRROR_URL=https://testnet.mirrornode.hedera.com/api/v1
NOMOS_GX402_HASHSCAN_BASE=https://hashscan.io/testnet
NOMOS_GX402_FACILITATOR_URL=https://api.testnet.blocky402.com
NOMOS_GX402_PORT=4402

NOMOS_GX402_PAY_TO=${payee.target}
NOMOS_GX402_PAYER_ACCOUNT_ID=${payer.target}
NOMOS_GX402_PAYER_KEY_PATH=.local/hedera-payer.key
NOMOS_GX402_PAYER_KEY_TYPE=ECDSA_SECP256K1

NOMOS_GX402_RECEIPT_SIGNING_KEY_PATH=.local/receipt-signer.key
NOMOS_GX402_RECEIPT_SIGNING_KID=nomos-gx402-demo-ed25519-1

NOMOS_GX402_PRICE_ATOMIC=${PRICE_ATOMIC}
NOMOS_GX402_MAX_ATOMIC_PER_PAYMENT=10000000
NOMOS_GX402_MAX_ATOMIC_CUMULATIVE=200000000
NOMOS_GX402_MAX_PAYMENTS_PER_UTC_DAY=50
NOMOS_GX402_QUOTE_TTL_SECONDS=180

NOMOS_GX402_HCS_TOPIC_ID=
NOMOS_GX402_ANCHOR_ENABLED=false
`;

  writeFileSync(resolve(".env"), env, { mode: 0o600 });
  console.log("\nwrote .env (mode 0600, git-ignored)");
  console.log("next: node tools/preflight-check.ts");
}

main().catch((e) => {
  console.error(`\nsetup-env: ${(e as Error).message}`);
  process.exit(1);
});
